name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - run: pnpm build
      - run: pnpm package

      - uses: PlasmoHQ/bpp@v3
        with:
          # see:
          # * https://docs.plasmo.com/framework/workflows/submit
          # * https://github.com/PlasmoHQ/bms/blob/main/tokens.md
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
